config/routes.rb
Chickens::Application.routes.draw do
  root :to => "chickens#index"
  resources :chickens

end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
validates_length_of :name, :minimum => 40
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chickens_controller.rb
class ChickensController < ApplicationController
  # GET /chickens
  # GET /chickens.json
  def index
    @chickens = Chicken.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chickens }
    end
  end

  # GET /chickens/1
  # GET /chickens/1.json
  def show
    @chicken = Chicken.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chicken }
    end
  end

  # GET /chickens/new
  # GET /chickens/new.json
  def new
    @chicken = Chicken.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chicken }
    end
  end

  # GET /chickens/1/edit
  def edit
    @chicken = Chicken.find(params[:id])
  end

  # POST /chickens
  # POST /chickens.json
  def create
    @chicken = Chicken.new(params[:chicken])

    respond_to do |format|
      if @chicken.save
        format.html { redirect_to @chicken, notice: 'Chicken was successfully created.' }
        format.json { render json: @chicken, status: :created, location: @chicken }
      else
        format.html { render action: "new" }
        format.json { render json: @chicken.errors, status: :unprocessable_entity }
        format.js {render action: "new"}
      end
    end
  end

  # PUT /chickens/1
  # PUT /chickens/1.json
  def update
    @chicken = Chicken.find(params[:id])

    respond_to do |format|
      if @chicken.update_attributes(params[:chicken])
        format.html { redirect_to @chicken, notice: 'Chicken was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @chicken.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chickens/1
  # DELETE /chickens/1.json
  def destroy
    @chicken = Chicken.find(params[:id])
    @chicken.destroy

    respond_to do |format|
      format.html { redirect_to chickens_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/views/chickens/_form.html.erb
<%= form_for @chicken, :remote => true do |f| %>
  <% if @chicken.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chicken.errors.count, "error") %> prohibited this chicken from being saved:</h2>

      <ul>
      <% @chicken.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chickens/edit.html.erb
<h1>Editing chicken</h1>

<%= render 'form' %>

<%= link_to 'Show', @chicken %> |
<%= link_to 'Back', chickens_path %>

app/views/chickens/index.html.erb
<h1>Listing chickens</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chickens.each do |chicken| %>
  <tr>
    <td><%= chicken.name %></td>
    <td><%= link_to 'Show', chicken %></td>
    <td><%= link_to 'Edit', edit_chicken_path(chicken) %></td>
    <td><%= link_to 'Destroy', chicken, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chicken', new_chicken_path %>

app/views/chickens/new.html.erb
<h1>New chicken</h1>

<%= render 'form' %>

<%= link_to 'Back', chickens_path %>

app/views/chickens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chicken.name %>
</p>


<%= link_to 'Edit', edit_chicken_path(@chicken) %> |
<%= link_to 'Back', chickens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chickens</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>